# strategies/base.py
"""
Base Strategy Interface

Defines the abstract protocol that all trading strategies must implement.
This ensures a consistent interface for the router to interact with.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class OrderInstruction:
    """
    A single order instruction generated by a strategy.

    Strategies produce these instructions; the router/executor decides
    whether and how to execute them.

    Attributes:
        side: Order direction - "BUY" or "SELL"
        size: Suggested order size (USD or units, depending on context)
        price: Suggested limit price, or None for market order
        meta: Optional metadata dict for strategy-specific information
              (e.g., platform, reason, confidence score, etc.)
    """
    side: str                   # "BUY" / "SELL"
    size: float
    price: Optional[float] = None   # None = market order
    meta: Optional[Dict[str, Any]] = None


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement the `on_tick` method which receives
    market state and returns a list of order instructions (possibly empty).

    Strategies should be pure logic:
    - No I/O (network calls, file reads)
    - No side effects (state changes outside the strategy)
    - Deterministic given the same inputs

    The router is responsible for:
    - Feeding market state to strategies
    - Deciding which strategy's instructions to execute
    - Actual order execution
    """

    def __init__(self, name: str = "base") -> None:
        self.name = name

    @abstractmethod
    def on_tick(self, market_state: Dict[str, Any]) -> List[OrderInstruction]:
        """
        Process a market tick and return order instructions.

        This method is called once per time step by the router/backtest engine.
        It should analyze the market state and return a list of order
        instructions if there's a trading opportunity.

        Args:
            market_state: Dictionary containing current market data.
                         The exact fields depend on the strategy type.
                         Common fields include prices, volumes, timestamps.

        Returns:
            List[OrderInstruction]: A list of order instructions to execute.
                                   Return an empty list if no action needed.
        """
        ...
